config:
  aws:region: us-west-2
  modernfi-rate-agent:fredApiKey:
    secure: AAABAH2n3F4y6CQq7nnBR/Lg3O5MjavSOEapTmLScBWI5TsIowNxmK2zisVrWWQNBlKmti3Q0EJWnbVDnEQdVw==
  modernfi-rate-agent:anthropicApiKey:
    secure: AAABAMLIB7gRMyc67vBWq9hjE5Ma6D0sBTaH4bxO9BvDV9D+b0ONc9g1dpOwyyYi8LAX+zwdZaTarlcBgreVQGuxgNzjRk79KkLsC2lHSUJd5xDOXW8zXVxMJtN4XiuHc0d8iKRuKzJUo0kEQvup1eYHY47wtl60pFXgEN7N/ZfYI2HAM2R/a3zH2yo=
  modernfi-rate-agent:anthropicModel: claude-haiku-4-5-20251001
  modernfi-rate-agent:dbPassword:
    secure: AAABAO/IubRebe9GADcWUP6taMLk3tS/7BFxLUFG91a2zWnpNin4qjM3ceBAfKgkLkEEqg==
